2d or 3d


In [2]:
import numpy as pr

In [7]:
a=pr.zeros(4)
print (a)

[0. 0. 0. 0.]


In [14]:
pr.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
pr.ones((3,4))
type(pr)

module

In [25]:
pr.ones([5,2])   ### 2d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
a=pr.zeros(((3,4,4,4)))
print(a)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [64]:

a=pr.ones((4,5))
print (a)
type(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


numpy.ndarray

In [70]:
a[1][1]=30
a[2][2]=30
a[3][3]=30

In [71]:
print(a)

[[ 1.  1.  1.  1.  1.]
 [ 1. 30.  1.  1.  1.]
 [ 1.  1. 30.  1.  1.]
 [ 1.  1.  1. 30.  1.]]


In [85]:
a[1][-1]=40

In [89]:
 print (a)

[[ 1.  1.  1.  1.  1.]
 [ 1. 30. 30.  1. 40.]
 [ 1.  1. 30. 40.  1.]
 [ 1. 40.  1. 30. 40.]]


In [99]:
b=pr.ones((3,5))

In [100]:
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [113]:
b[1][1]=10
b[2][4]=70

In [114]:
print(b)

[[ 1.  1.  1.  1.  1.]
 [ 1. 10.  1.  1.  1.]
 [ 1.  1. 20.  1. 70.]]


In [123]:
v=pr.full((4,5),100)
print (v)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [134]:
v=pr.full((4,5),(23))
print (v)

[[23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]]


In [139]:
b=pr.eye(4,4)   ## main  diogonal
print (b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [148]:
a=pr.random.randint(10,50,(3,3))
print (a)


[[38 21 10]
 [17 31 29]
 [40 25 33]]


In [150]:
n=pr.random.randint(10,50,(3,3))
print (n)

[[20 34 32]
 [46 17 41]
 [20 45 28]]


In [163]:
b=pr.trapz(a)
print (b)

[45.  54.  61.5]


In [165]:
b=pr.trace(n)
print (b)

65


In [171]:
b=pr.transpose(a)
print (b)

[[38 17 40]
 [21 31 25]
 [10 29 33]]


In [172]:
# termiology related to numpy array
#1 fuction >>>..... np funname ( array)
#2 method >>>>>>....... array methodname
#3 porperty >>>>....... .array.porperty

In [200]:
print(b.ndim)
print (len(b))
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)

2
3
2
9
(3, 3)
int32


In [8]:
import numpy as pr
v=pr.random.randint(20,100000,10)
print (v)

[77605  7038 39309  8218 50226 63262 52923 81200 44923 47106]


In [18]:
v[v>=40000] 


array([77605, 50226, 63262, 52923, 81200, 44923, 47106])

#import numpy as np

In [241]:
import numpy as np

In [242]:
h=np.random.randint (1,10,(3,4))
print(h)

[[2 7 1 8]
 [2 9 9 1]
 [9 5 6 5]]


In [243]:
np.resize(h,(4,5))

array([[2, 7, 1, 8, 2],
       [9, 9, 1, 9, 5],
       [6, 5, 2, 7, 1],
       [8, 2, 9, 9, 1]])

In [244]:
np.resize(h,(3,7))

array([[2, 7, 1, 8, 2, 9, 9],
       [1, 9, 5, 6, 5, 2, 7],
       [1, 8, 2, 9, 9, 1, 9]])

fuction

In [246]:
h.resize(3,7,refcheck=False)
h

array([[2, 7, 1, 8, 2, 9, 9],
       [1, 9, 5, 6, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [247]:
h.resize(4,5,refcheck=False)
h

array([[2, 7, 1, 8, 2],
       [9, 9, 1, 9, 5],
       [6, 5, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [248]:
import sys 
np.resize(a,(7,4))
print(type(m))

<class 'numpy.ndarray'>


In [249]:
g=sys.getsizeof(m)
g

128

In [250]:
n=list(m)
print(n)

[array([6, 7, 4, 8, 6]), array([8, 1, 1, 7, 5]), array([7, 8, 0, 0, 0]), array([0, 6, 7, 4, 8]), array([6, 8, 1, 1, 7]), array([5, 7, 8, 0, 0])]


In [251]:
print (type(n))

<class 'list'>


In [252]:
sys.getsizeof(n)

104

In [253]:
w=np.random.randint (1,10,(3,4))
print(w)

[[1 3 3 3]
 [8 6 2 2]
 [1 9 7 8]]


In [254]:
(w.sum),w.sum(axis=0)

(<function ndarray.sum>, array([10, 18, 12, 13]))

In [255]:
(w.sum(),w.sum(axis=0),w.sum(axis=1))

(53, array([10, 18, 12, 13]), array([10, 18, 25]))

In [256]:
(w.min(),w.min(axis=0),w.min(axis=1))

(1, array([1, 3, 2, 2]), array([1, 2, 1]))

In [257]:
print (w.max),w.max(axis=0)

<built-in method max of numpy.ndarray object at 0x000002026B3B8210>


(None, array([8, 9, 7, 8]))

In [258]:
w.argmax()

9

In [259]:
w.flatten()

array([1, 3, 3, 3, 8, 6, 2, 2, 1, 9, 7, 8])

In [260]:
np.square(w)

array([[ 1,  9,  9,  9],
       [64, 36,  4,  4],
       [ 1, 81, 49, 64]])

In [261]:
w

array([[1, 3, 3, 3],
       [8, 6, 2, 2],
       [1, 9, 7, 8]])

In [262]:
np.sqrt(w)

array([[1.        , 1.73205081, 1.73205081, 1.73205081],
       [2.82842712, 2.44948974, 1.41421356, 1.41421356],
       [1.        , 3.        , 2.64575131, 2.82842712]])

In [263]:
h=np.random.randint (1,10,(3,4))
print(h)

[[3 8 4 8]
 [8 5 5 1]
 [9 6 1 8]]


In [264]:
w=np.random.randint (1,10,(3,4))
print(w)

[[5 3 1 2]
 [1 4 4 8]
 [6 8 1 5]]


In [265]:
w*3

array([[15,  9,  3,  6],
       [ 3, 12, 12, 24],
       [18, 24,  3, 15]])

In [266]:
w-3

array([[ 2,  0, -2, -1],
       [-2,  1,  1,  5],
       [ 3,  5, -2,  2]])

In [267]:
w

array([[5, 3, 1, 2],
       [1, 4, 4, 8],
       [6, 8, 1, 5]])

In [268]:
w**2

array([[25,  9,  1,  4],
       [ 1, 16, 16, 64],
       [36, 64,  1, 25]])

In [269]:
w+70

array([[75, 73, 71, 72],
       [71, 74, 74, 78],
       [76, 78, 71, 75]])

In [285]:
a=np.random.randint (1,10,(3,3))
b=np.random.randint (1,10,(3,5))
print(a)
print(b)

[[2 7 4]
 [6 7 5]
 [2 3 4]]
[[5 7 3 7 6]
 [4 9 4 9 8]
 [1 5 3 8 6]]


In [286]:
a@b

array([[ 42,  97,  46, 109,  92],
       [ 63, 130,  61, 145, 122],
       [ 26,  61,  30,  73,  60]])

numpy 3d array

In [292]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [314]:
a=np.random.randint(1,10,(3,5,5,7,4))
print (a)

[[[[[9 4 6 3]
    [7 2 6 6]
    [2 8 2 4]
    ...
    [2 8 1 6]
    [4 5 9 3]
    [2 9 5 4]]

   [[4 1 8 5]
    [2 4 5 4]
    [9 9 8 4]
    ...
    [3 7 8 9]
    [6 5 8 4]
    [5 5 9 8]]

   [[3 4 7 2]
    [7 5 8 4]
    [1 9 8 9]
    ...
    [3 3 9 1]
    [8 6 2 8]
    [1 4 1 7]]

   [[9 5 4 6]
    [1 8 1 6]
    [3 7 2 9]
    ...
    [3 5 3 3]
    [8 5 8 7]
    [1 7 1 3]]

   [[4 6 9 7]
    [9 8 8 6]
    [6 7 3 3]
    ...
    [4 9 7 8]
    [4 5 1 8]
    [6 9 6 6]]]


  [[[6 6 5 5]
    [1 9 5 6]
    [7 8 3 3]
    ...
    [6 1 3 8]
    [2 3 7 8]
    [4 7 2 7]]

   [[4 5 2 9]
    [4 5 1 3]
    [7 3 2 5]
    ...
    [1 2 9 2]
    [1 6 8 1]
    [5 7 5 2]]

   [[1 3 6 2]
    [9 8 5 2]
    [9 4 2 9]
    ...
    [4 2 5 1]
    [3 5 6 2]
    [9 4 8 8]]

   [[2 2 3 9]
    [9 4 1 9]
    [9 9 2 8]
    ...
    [3 1 1 1]
    [5 6 2 2]
    [8 6 3 1]]

   [[2 5 6 9]
    [2 8 9 6]
    [3 3 5 3]
    ...
    [5 2 5 7]
    [3 4 8 8]
    [7 4 6 6]]]


  [[[1 7 1 7]
    [5 3 5 3]
    [2 2 2 8]
    ...
    [7