In [1]:
# array


In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
np.__version__

'1.25.0'

In [5]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
type(a)

numpy.ndarray

In [7]:
a=np.array([1,2,3,4,10.5,'prashant'])  #ONE STR AND ALL VALUEES STR CONVERT
print(a)

['1' '2' '3' '4' '10.5' 'prashant']


In [8]:
a=np.array([1,2,3,4,10.5,])  #ONE VALUES FLOAT AND ALL VALUES FLOAT CONVERT
print(a)

[ 1.   2.   3.   4.  10.5]


In [9]:
a=[1,2,3,4,6,7]

In [10]:
print(a)    # list with sep comma
print(type(a))

[1, 2, 3, 4, 6, 7]
<class 'list'>


In [11]:
type(a)

list

In [12]:
a=np.array([1,23,4,5,6,7,8,9])    ## array with not sep comma
print(a)

[ 1 23  4  5  6  7  8  9]


In [13]:
a=np.array([1,2,3,"prashant"])

In [14]:
print(a) 

['1' '2' '3' 'prashant']


In [15]:
a=np.array([1,2,3,"prashant",18.6,3.5,6.7])

In [16]:
print(a)

['1' '2' '3' 'prashant' '18.6' '3.5' '6.7']


In [17]:
a=np.array([1,2,3,18.6,3.5,6.7])     ## ONE VALUES FLOAT AND ALL VALUES FLOAT CONVERT

In [18]:
print (a)

[ 1.   2.   3.  18.6  3.5  6.7]


In [19]:
a=np.array([1,2,3,4,5],dtype=np.int16)

In [20]:
print(a)
print (type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
a=np.array([1,2,3,4,5],dtype=np.float32)

In [22]:
print (a)

[1. 2. 3. 4. 5.]


In [23]:
m=np.array([1,2,3,"prashant",4,5],dtype=np.int16)   
# not change str beacuse base 10 

ValueError: invalid literal for int() with base 10: 'prashant'

In [24]:
b=np.array([1,2,3,1.90,4,5],dtype=np.int16)
print (a)      ## that int and one value float  add b varibles store cannot covert float because dtype fuction all values int covert
type(a)



[1. 2. 3. 4. 5.]


numpy.ndarray

In [25]:
b=np.array([1,2,3,4,5,"prashant"],dtype=np.int16)

ValueError: invalid literal for int() with base 10: 'prashant'

In [30]:
b=np.array(["1,34,5,6,7,8,9"],dtype=np.str16)

AttributeError: module 'numpy' has no attribute 'str16'

In [34]:
b=np.array([1,3,4,5,6,7,8,9],dtype=np.float64)

In [36]:
print (b)
print(type(b))

[1. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [43]:
b=np.array([1,3,4,5,6,7,8,9],dtype=np.int32)

In [46]:
print(b)
print (type(b))

[1 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [61]:
n=np.array([-1,-4,5,6,7,8,9],dtype=np.int8)
print (n)

[-1 -4  5  6  7  8  9]


In [66]:
p=np.array([-1,2,3,4,5,6],dtype=np.uint8)
print(p)

[255   2   3   4   5   6]


C:\Users\Gaurav\AppData\Local\Temp\ipykernel_4120\3396923315.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  p=np.array([-1,2,3,4,5,6],dtype=np.uint8)


In [67]:
p=np.array([-1,2,3,4,5,6],dtype=np.uint16)
print(p)

[65535     2     3     4     5     6]


C:\Users\Gaurav\AppData\Local\Temp\ipykernel_4120\134499628.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  p=np.array([-1,2,3,4,5,6],dtype=np.uint16)


In [68]:
p=np.array([-1,2,3,4,5,6],dtype=np.uint128)
print(p)

AttributeError: module 'numpy' has no attribute 'uint128'

In [69]:
### arange 

In [84]:
e=np.arange(10,100,100)
print(e)

[10]


In [85]:
e=np.arange(10,100,10)
print(e)

[10 20 30 40 50 60 70 80 90]


In [88]:
e=np.arange(10,-100,10)    ## stop values negtive
print(e)

[]


In [93]:
e=np.arange(-10,100,10)   ##starting values postive
print(e)

[-10   0  10  20  30  40  50  60  70  80  90]


In [94]:
e=np.arange(10,100,100)
print(e)

[10]


In [97]:
e=np.arange(10,1000)
(e)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 19

In [102]:
e=np.arange(-104,1006,100)
print(e)

[-104   -4   96  196  296  396  496  596  696  796  896  996]


In [113]:
e=np.arange({10,100,1.00},dtype=np.float16)    #  does not does support dtype ( arange)
print(e)

TypeError: unsupported operand type(s) for -: 'set' and 'int'

In [124]:
import numpy as np

In [142]:
y=list(range(5000))
x=np.arange (9000)

In [143]:
import sys

In [144]:
print (sys.getsizeof(y))
print( sys.getsizeof(x))

40056
36112


In [172]:
a=np.array([5000,3000,4000,6000,9000])

In [173]:
print (a)

[5000 3000 4000 6000 9000]


In [174]:
a=a+500

In [175]:
print (a)

[5500 3500 4500 6500 9500]


In [220]:
i=np.array([5000,3000,-4000,6000,9000])
print (i)
type(i)

[ 5000  3000 -4000  6000  9000]


numpy.ndarray

In [221]:
i[i<=5000]
type(i)

numpy.ndarray

In [222]:
i[i>=5000]
print (np.where(a>=5000))
print(np.where(a<=5000))
print (np.where(a==5000))
type(i)

(array([0, 3, 4], dtype=int64),)
(array([1, 2], dtype=int64),)
(array([], dtype=int64),)


numpy.ndarray

In [223]:
i=i+100

In [224]:
print(i)

[ 5100  3100 -3900  6100  9100]


In [226]:
##        |method

In [229]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [235]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [246]:
a=np.zeros(("69","79"))    ## dose not support str

TypeError: 'str' object cannot be interpreted as an integer

In [242]:
(a)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [250]:
a=np.zeros([-2,7])   ## negative dimension are not allowed
print(a)

ValueError: negative dimensions are not allowed

In [256]:
a=np.zeros([3,3],dtype=np.int16)
print(a)
type(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


numpy.ndarray

In [258]:
a=np.zeros([3,3],dtype=np.float128)
print(a)
type(a)

AttributeError: module 'numpy' has no attribute 'float128'

In [261]:
a=np.zeros([3,3],dtype=np.float32)
print(a)
type(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


numpy.ndarray

In [264]:
b=np.ones([])    #by default float
print (b)

1.0


In [273]:
c=np.ones([6,6])
print(c)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [283]:
c=np.ones([4,4],dtype=np.int16)
print(c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [296]:
v=np.full (10,500)
print (v)

[500 500 500 500 500 500 500 500 500 500]


In [297]:
print( sys.getsizeof(v))


152


In [311]:
a=np.linspace(10,100,5)
print(a)

[ 10.   32.5  55.   77.5 100. ]


In [315]:
a=np.linspace(1,50)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [6]:
import numpy as np

In [7]:
a=np.linspace(10,100,5)
print (a)

[ 10.   32.5  55.   77.5 100. ]


In [8]:
a=np.linspace(0,50,10)
print (a)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [9]:
a=np.random .randint(10,50,5)
print(a)

[46 28 20 29 21]


In [10]:
b=np.random.randint(10,50,5)
print(b)

[12 18 19 26 26]


In [13]:
a*b

array([552, 504, 380, 754, 546])

In [14]:
a+b

array([58, 46, 39, 55, 47])

In [32]:
np.any([a]),a.any()
np.all([b]),b.all()

(True, True)

In [11]:

#concatiation
c=a+b

In [12]:
print(a)

[46 28 20 29 21]


In [2]:
import numpy as np

In [17]:
a=np.loadtxt("E:\prashant.txt")

ValueError: could not convert string '10,20,30,40,50,60' to float64 at row 0, column 1.

In [18]:
print(a)

[15 57 50 86 18 69 38 24 77 95]


In [19]:
np.random.uniform(1,10,5)

array([1.36130926, 4.58386145, 1.88319479, 6.15153691, 9.47975344])

In [20]:
m=np.random.randint(1,10,5)
print (m)

[1 6 6 2 7]


In [21]:
k=np.square(m)
print(k)

[ 1 36 36  4 49]


In [22]:
v=np.sqrt(k)
print(v)

[1. 6. 6. 2. 7.]


In [23]:
a=np.random.randint(10,100,10)
print (a)

[33 34 57 72 95 20 49 46 66 68]


In [26]:
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))

540
95
20
54.0
53.0


In [27]:
## index based
# boolean condition based



In [28]:
a[2:1]

array([], dtype=int32)

In [29]:
print(a)

[33 34 57 72 95 20 49 46 66 68]


In [30]:
a[1:2]

array([34])

In [31]:
a[::2]

array([33, 57, 95, 49, 66])

In [35]:
a[::1]

array([33, 34, 57, 72, 95, 20, 49, 46, 66, 68])

In [37]:
a[::4]

array([33, 95, 66])

In [38]:
a[1:4]

array([34, 57, 72])

In [39]:
a[2:4]

array([57, 72])

In [40]:
a

array([33, 34, 57, 72, 95, 20, 49, 46, 66, 68])

In [43]:
a[3:4]

array([72])

In [48]:
print(a[a>=45])

[57 72 95 49 46 66 68]


In [49]:
print(a>=100)

[False False False False False False False False False False]


In [70]:
print(a>=50)     ## boolean 

[False False  True  True  True False False False  True  True]


In [2]:
import numpy as np
import array as a

In [3]:
print(a[(a<=50) | (a>=95)])

TypeError: '<=' not supported between instances of 'module' and 'int'

In [4]:
print (np[np>=50 & np%2==0])

TypeError: unsupported operand type(s) for %: 'module' and 'int'

In [5]:
a=np.random.randint(100,1000,10)
print(a)

[680 625 628 683 528 576 113 225 298 145]


In [6]:
a.any()

True

In [7]:
a.all()

True

In [8]:
type(a)

numpy.ndarray

numpy concatenate v stack and, h stack

In [2]:
import  numpy as np

In [16]:
a=np.random.randint( 1,10,((3,3)))
b=np.random.randint( 1,10,((3,3)))

In [17]:
print( a)
print(b)

[[2 8 6]
 [5 6 6]
 [6 8 7]]
[[1 6 6]
 [9 4 3]
 [3 9 8]]


In [18]:
np.stack(a)

array([[2, 8, 6],
       [5, 6, 6],
       [6, 8, 7]])

In [19]:
np.stack(b)

array([[1, 6, 6],
       [9, 4, 3],
       [3, 9, 8]])

In [20]:
np.stack( (a,b))

array([[[2, 8, 6],
        [5, 6, 6],
        [6, 8, 7]],

       [[1, 6, 6],
        [9, 4, 3],
        [3, 9, 8]]])

In [21]:
np.hstack(a)

array([2, 8, 6, 5, 6, 6, 6, 8, 7])

In [22]:
np.hstack(b)

array([1, 6, 6, 9, 4, 3, 3, 9, 8])

In [24]:
np.hstack((a,b))

array([[2, 8, 6, 1, 6, 6],
       [5, 6, 6, 9, 4, 3],
       [6, 8, 7, 3, 9, 8]])

concatenate

In [25]:
np.concatenate((a,b))

array([[2, 8, 6],
       [5, 6, 6],
       [6, 8, 7],
       [1, 6, 6],
       [9, 4, 3],
       [3, 9, 8]])

In [36]:
m=np.append(a,3)
((m))
print(m)

[2 8 6 5 6 6 6 8 7 3]


In [61]:
np.append(a,10)

array([30, 30, 44, 44, 30,  5,  6, 70,  6, 80,  7, 10])

In [63]:
np.append(a,0)

array([30, 30, 44, 44, 30,  5,  6, 70,  6, 80,  7,  0])

second method add values 

In [40]:
a[0]=30
a

array([[30, 30, 30],
       [ 5,  6,  6],
       [ 6,  8,  7]])

In [47]:
a[1][2]=70
a

array([[30, 30, 30],
       [ 5,  6, 70],
       [ 6,  8,  7]])

In [49]:
a[0][2]=40
print(a)

[[30 30 40]
 [ 5  6 70]
 [ 6  8  7]]


In [51]:
a[-1][1]=80
a

array([[30, 30, 40],
       [ 5,  6, 70],
       [ 6, 80,  7]])

In [53]:
a[0][-1]=30
a

array([[30, 30, 30],
       [ 5,  6, 70],
       [ 6, 80,  7]])

In [56]:
a=np.insert(a,2,44)
a

array([30, 30, 44, 44, 30,  5,  6, 70,  6, 80,  7])

In [57]:
np.insert(a,2,88)

array([30, 30, 88, 44, 44, 30,  5,  6, 70,  6, 80,  7])

In [58]:
print(a)

[30 30 44 44 30  5  6 70  6 80  7]


In [64]:
np.delete(a,2)

array([30, 30, 44, 30,  5,  6, 70,  6, 80,  7])

In [65]:
np.delete(a,7)

array([30, 30, 44, 44, 30,  5,  6,  6, 80,  7])

In [67]:
np.delete(a,3)

array([30, 30, 44, 30,  5,  6, 70,  6, 80,  7])